import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../frontend/static/client_controls.js',import.meta.url),'utf8');
const {default:render}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const listeners=new Map(),stored=new Map(),p={textContent:'☾ Dark mode'},tip={dataset:{}};
let style,dispatched;
globalThis.document={documentElement:{dataset:{}},head:{appendChild:s=>style=s},getElementById:()=>style,createElement:()=>({}),querySelector:()=>p,querySelectorAll:()=>[tip],addEventListener:(k,v)=>listeners.set(k,v),removeEventListener:k=>listeners.delete(k)};
globalThis.window={dispatchEvent:e=>dispatched=e};
globalThis.CustomEvent=class{constructor(type,data){this.type=type;this.detail=data.detail;}};
globalThis.localStorage={getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)};
const data={fallback:'light',palettes:{light:{surface:'#fff'},dark:{surface:'#123'}}};
let cleanup=render({data});let stopped=false;
listeners.get('click')({target:{closest:()=>true},preventDefault(){},stopImmediatePropagation(){stopped=true;}});
assert.equal(stopped,true);assert.equal(stored.get('trace.pet.theme.v1'),'dark');assert.match(style.textContent,/#123/);assert.equal(p.textContent,'☀ Light mode');assert.equal(dispatched.detail.mode,'dark');
listeners.get('keydown')({key:'Escape'});assert.equal(tip.dataset.dismissed,'true');
listeners.get('pointerout')({target:{closest:()=>tip}});assert.equal(tip.dataset.dismissed,undefined);
cleanup();assert.equal(listeners.size,0);
p.textContent='☾ Dark mode';cleanup=render({data});assert.equal(p.textContent,'☀ Light mode');cleanup();
console.log('Client-only theme toggle, persisted appearance, tooltip dismissal and listener cleanup passed.');
