"""Short, editable explanations shared by the UI's immediate help tooltips."""

HELP = {
    "task_mode": "Auto lets the backend choose a workflow from the question and evidence. Evidence investigation analyzes supplied records. Idea review uses a fixed research, support and challenge team to examine a proposal without treating arguments as validated findings.",
    "discussion": "A real sequence of research, support, challenge and revision messages from this run. Assumptions and questions remain proposals until checked against evidence. Perspectives describe the agents' jobs, not whether their claims are correct.",
    "weak_points": "Backend-reported limits in this run's evidence, findings or sources. Inspect the cited findings and references. This is not an independent literature review or a complete audit of possible weaknesses. Older recordings may not contain an assessment.",
    "source": "Try the demo runs a new workflow on sample evidence with your question and simulated model outputs. Recorded cases replay saved activity. Investigate my data connects to your backend.",
    "recorded_case": "Each case includes its original question, evidence and agent outputs. Replaying it does not call a model or analyze new files.",
    "playback_speed": "Controls how quickly recorded events appear. Higher values play faster without changing the saved result.",
    "backend": "The address of the investigation service. It provides the available agents and models and receives your files when you start a run.",
    "sample": "Use the example evidence bundled with the backend. Your selected uploads are kept in the draft but are not used while this is enabled.",
    "uploads": "Select one or more evidence files for the same investigation. They stay in your draft when you move between steps and are sent to the backend when you start.",
    "question": "Describe what you want to understand, including the biological context and the evidence you want agents to examine. You can edit this before starting.",
    "recorded_question": "This is the question used in the saved case. Choose Try the demo or Investigate my data in the evidence step to ask your own question.",
    "agent_setup": "Choose the specialists for this run. The planner coordinates their work and the critic reviews whether the evidence supports the conclusion.",
    "specialists": "Each selected specialist adds one agent to the investigation. Required agents remain active. These settings apply when you start a new run.",
    "reasoning_model": "Used by the planner, specialists and critic to reason over the evidence. Enter a model ID supported by the server's provider, or leave blank for its default.",
    "variant_model": "Used for genomic variant analysis. Enter a model ID supported by the server's variant provider, or leave blank for its default.",
    "embedding_model": "Turns literature text into numerical representations for retrieval. Enter a model ID supported by the server's embedding provider, or leave blank for its default.",
    "network": "Each node is an agent. Solid arrows show which agent created another; dashed arrows show messages. This is a workflow view, not a map of biological causes.",
    "messages": "Recorded messages between agents show how they share evidence and review findings. The panel shows the latest exchanges; the activity timeline includes tool activity too.",
    "findings": "Claims produced by individual agents, ordered by confidence. Open a finding's provenance to inspect its attached sources before relying on the claim.",
    "confidence": "A model or heuristic score of support, not a calibrated probability of correctness. High starts at 0.70, moderate at 0.40; missing scores are marked unscored.",
    "provenance": "The sources attached to this finding, such as file references, records or paper identifiers. A source reference lets you trace a claim; it does not by itself establish causation.",
    "verdict": "The final conclusion synthesizes the agents' findings. Abstained means the critic judged the available evidence insufficient to support an answer.",
    "run_config": "The settings reported by this run, including its agents, models and execution mode when available. Editing the setup later does not alter this saved result.",
    "timeline": "Agent messages, tool calls and other activity from the run. Times are relative to the first event; the most recent activity appears first.",
    "raw_events": "The event records used to build this view. They are useful for tracing what happened or debugging a run; they are not additional scientific evidence.",
}
